# Generated by Django 5.0.1 on 2024-01-09 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_document_date_completed_alter_document_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedded_successfully',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_chatted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 1, 8, 1, 474676, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_completed',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 1, 8, 1, 474425, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 1, 8, 1, 474250, tzinfo=datetime.timezone.utc)),
        ),
    ]
