# Generated by Django 5.0.1 on 2024-01-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_embeddedchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message_id',
            field=models.CharField(default='msg_0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
