# Generated by Django 5.0.1 on 2024-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='doc', max_length=100),
            preserve_default=False,
        ),
    ]
