# Generated by Django 5.0.1 on 2024-01-08 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_when_chat_date_chatted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_completed',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 17, 36, 37, 332476)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 17, 36, 37, 332465)),
        ),
    ]
